@echo off
setlocal EnableExtensions EnableDelayedExpansion

rem CPrime Cost worker: run codex in the foreground, one work cycle at a time,
rem and drive down the time cpc.exe takes to compile.
rem
rem Scope: how long root cpc.exe takes to build itself and to compile C and C++
rem translation units, hardest case first: heavy headers, heavy template
rem instantiation, deep constant evaluation, macro-heavy preprocessing, large
rem translation units, deep call graphs and repeated declaration lookups.
rem
rem Codex decides what to change. This script only checks, measures, reports and
rem loops; Cost\task.md holds the goal, the measurement commands, the rules and
rem the current leads, and codex keeps it current as work completes.
rem
rem This loop is additive and never destructive. It creates Cost\build,
rem writes its own logs there, and never deletes, moves or renames any file. It
rem never creates the stop marker: only you do. A failed cycle leaves the tree
rem committed and usable, so the next cycle, or the next day, continues from
rem where it stopped instead of starting over.
rem
rem Three machines share one branch. This clone is the Cost arm of a
rem multi-machine loop in which other clones run the Capability and Compatibility
rem workers against the same origin, so this script owns every git operation at
rem the cycle boundary. Run one worker per clone, never two in one working tree:
rem they share the same index. The first cycle commits whatever the tree already
rem holds, so start from a clean tree or expect that work to be committed as
rem "<Cost> cycle 0".
rem
rem Sync at the top of every cycle, in this order:
rem   1. commit the work of the cycle that just ended,
rem   2. fetch the shared branch,
rem   3. rebase this clone's unpushed commits onto it,
rem   4. push them back.
rem Only a cycle whose probe passed is published, so the branch keeps trees that
rem passed their own gate; a failed probe leaves the commits local for the cycle
rem that repairs them. Set PUSH_FAILED=1 to publish anyway.
rem
rem Rebase conflicts are split by kind. Tracked build outputs - cpc.exe,
rem src/lib/libcprime1.a, src/scripts/*.exe, Cost/tests/test.exe - are
rem regenerated by the build, so this clone keeps its own copy and continues. A
rem conflict in a source file is real work that cannot be dropped: the rebase is
rem left in place and codex resolves it at the start of the cycle, before it
rem touches the task. Work is never lost either way.
rem
rem A refused push means another machine published first, so the worker fetches,
rem rebases onto the new tip and pushes again.
rem
rem Optional environment overrides:
rem   DONE             stop marker file (default Cost\done.x)
rem   CODEX_EXE        codex executable (default %USERPROFILE%\.local\bin\deepseek.exe)
rem   MODEL            model name for codex (default: codex configuration)
rem   REASONING        model reasoning effort (default high)
rem   TASK_PROMPT      prompt handed to codex (default: continue Cost\task.md)
rem   MAX_CYCLES       stop after N cycles this session, 0 = unlimited (default 0)
rem   FAIL_EXIT_LIMIT  stop after N consecutive nonzero codex exits, 0 = keep going (default 5)
rem   FAIL_SLEEP       seconds to wait after a failed cycle (default 60)
rem   CHECK_ARGS       per-cycle correctness probe (default "-All -Tier fast")
rem   PERF_ARGS        per-cycle speed measurement (default below)
rem   NO_CHECK         set to 1 to skip the per-cycle correctness probe
rem   NO_MEASURE       set to 1 to skip the per-cycle speed measurement
rem   SKIP_COMMIT      set to 1 to leave the tree dirty instead of committing (default 0)
rem   SKIP_SYNC        set to 1 to keep this clone offline: no fetch, rebase or push
rem   SKIP_PUSH        set to 1 to fetch and rebase but never push
rem   PUSH_FAILED      set to 1 to publish even after a failed probe (default 0)
rem   REMOTE           git remote shared with the other machines (default origin)
rem   BRANCH           branch shared with the other machines (default the current branch)
rem   SYNC_TRIES       push attempts per cycle before deferring to the next (default 4)
rem   SYNC_SLEEP       seconds between two push attempts (default 5)
rem
rem Logs live in Cost\build: cycles.csv has one row per cycle,
rem cycle-NNNN.log is the full codex transcript, cycle-NNNN-result.txt its final
rem message, cycle-NNNN-check.log the probe output, perf-cycle-NNNN.tsv the
rem per-case compile times of that cycle, sync.log the last fetch or rebase,
rem sync-push.log the last push and gate-state.txt the probe result the next
rem cycle publishes on, so a restart cannot publish a tree that failed.

set "AREA=cost"
set "TITLE=Cost"
set "GOAL=drive down the time cpc.exe takes to build itself and to compile C and C++ sources"

cd /d "%~dp0.."
set "ROOT=%CD%"

if not defined DONE set "DONE=%TITLE%\done.x"
rem DeepSeek is the working account for this loop; set CODEX_EXE to run another one.
if not defined CODEX_EXE set "CODEX_EXE=%USERPROFILE%\.local\bin\deepseek.exe"
if not defined REASONING set "REASONING=high"
if not defined TASK_PROMPT set "TASK_PROMPT=Read %TITLE%\task.md and continue its earliest unfinished work package, following AGENTS.md. Use only root cpc.exe, one compiler process at a time. Measure before and after with the commands %TITLE%\task.md names and keep the evidence under Cost\build. Finish by updating %TITLE%\task.md with the remaining work and the exact next action. Never create %TITLE%\done.x and never delete, move or rewrite %TITLE%\worker.cmd. The worker owns git at the cycle boundary: do not run git add, git commit, git fetch, git pull, git rebase or git push yourself."
if not defined MAX_CYCLES set "MAX_CYCLES=0"
if not defined FAIL_EXIT_LIMIT set "FAIL_EXIT_LIMIT=5"
if not defined FAIL_SLEEP set "FAIL_SLEEP=60"
if not defined CHECK_ARGS set "CHECK_ARGS=-All -Tier fast"
if not defined PERF_ARGS set "PERF_ARGS=-CpcOnly -NoGate -Quiet"
if not defined REMOTE set "REMOTE=origin"
if not defined SYNC_TRIES set "SYNC_TRIES=4"
if not defined SYNC_SLEEP set "SYNC_SLEEP=5"
if not defined SKIP_SYNC set "SKIP_SYNC=0"
if not defined SKIP_PUSH set "SKIP_PUSH=0"
if not defined PUSH_FAILED set "PUSH_FAILED=0"

set "LOG_DIR=%ROOT%\%TITLE%\build"
set "CYCLES=%LOG_DIR%\cycles.csv"
set "PERF_PREFIX=%LOG_DIR%\perf-cycle-"
set "SYNC_LOG=%LOG_DIR%\sync.log"
set "PUSH_LOG=%LOG_DIR%\sync-push.log"
set "CHECK_EXE=%ROOT%\%TITLE%\tests\test.exe"
set "GATE_EXE=%ROOT%\Compatibility\tests\test.exe"
if not defined GATE set "GATE=1"
set "SESSION=0"
set "FAILS=0"
set "RC=0"
set "CHECK_RC=-"
set "GATE_RC=-"
set "MEASURE_RC=-"
set "HEAD=-"
set "TAG=0000"
set "LAST_CHECK_OK=1"
set "SYNC_STATE=-"
set "SYNC_RC=0"
set "PUSH_RC=-"
set "SYNC_TRIES_RUN=0"
set "CONFLICT_LIST="
set "CONFLICT_COUNT=0"
set "RESOLVED_COUNT=0"
set "CONFLICT_SOURCE=0"
set "CONFLICT_PROMPT="
set "REBASE_ACTIVE=0"
set "REBASE_RC=0"
set "BEHIND=0"
set "AHEAD=0"
set "GENERATED=0"
set "PROMPT_KIND=task"
set "PULLED=0"
set "NEW_UPSTREAM=0"
set "PULL_NOTE=Other machines published work since this clone last ran and the rebase just brought it in, so root cpc.exe and the tracked executables may not match the sources you now see. Rebuild with src\scripts\build.exe before measuring or publishing a change, and re-run the affected checks against the merged tree."

if not exist "%LOG_DIR%" mkdir "%LOG_DIR%" >nul 2>&1
rem The publish rule outlives the process: only a tree whose last probe passed
rem is pushed, and a restart must not forget that the tree is still broken.
if exist "%LOG_DIR%\gate-state.txt" set /p LAST_CHECK_OK=<"%LOG_DIR%\gate-state.txt"

git rev-parse --git-dir >nul 2>&1
if errorlevel 1 (
    echo [%DATE% %TIME%] not a git repository: %ROOT%
    exit /b 1
)

call :git_setup
call :resolve_branch

call "%CODEX_EXE%" --version >nul 2>&1
if errorlevel 1 (
    echo [%DATE% %TIME%] cannot run codex "%CODEX_EXE%"; install it, or set CODEX_EXE to it.
    echo [%DATE% %TIME%] nothing was changed.
    exit /b 1
)

for /f "delims=" %%H in ('git rev-parse --short HEAD 2^>nul') do set "HEAD=%%H"
call :read_last

echo [%DATE% %TIME%] ==========================================================
echo [%DATE% %TIME%] CPrime %TITLE% worker starting
echo [%DATE% %TIME%] goal        : %GOAL%
echo [%DATE% %TIME%] task file   : %TITLE%\task.md
echo [%DATE% %TIME%] directory   : %ROOT%
echo [%DATE% %TIME%] codex       : %CODEX_EXE% ^(effort %REASONING%^)
echo [%DATE% %TIME%] cycle logs  : %LOG_DIR%\cycle-NNNN.log
echo [%DATE% %TIME%] cycle rows  : %CYCLES%
echo [%DATE% %TIME%] probe       : %CHECK_EXE% %CHECK_ARGS%
if "%GATE%"=="1" echo [%DATE% %TIME%] gate        : %GATE_EXE% -Regression
echo [%DATE% %TIME%] stop marker : %DONE% ^(create this file to stop after the current cycle^)
echo [%DATE% %TIME%] pacing      : codex runs in the foreground; the next cycle starts when it exits
echo [%DATE% %TIME%] shared      : %UPSTREAM% ^(fetch, rebase and push at each cycle boundary^)
echo [%DATE% %TIME%] publish     : only after a passing probe; PUSH_FAILED=1 publishes anyway
echo [%DATE% %TIME%] one at once : one worker per clone; the three clones meet in %UPSTREAM%
if defined LASTROW echo [%DATE% %TIME%] last cycle  : !LASTROW!
call :show_measure
echo [%DATE% %TIME%] ==========================================================

:cycle
call :commit_work
call :sync
if exist "%DONE%" (
    echo.
    echo [%DATE% %TIME%] "%DONE%" is present; stopping after cycle !CYCLE!.
    exit /b 0
)
if %MAX_CYCLES% gtr 0 if !SESSION! geq %MAX_CYCLES% (
    echo.
    echo [%DATE% %TIME%] session limit %MAX_CYCLES% reached after cycle !CYCLE!.
    exit /b 0
)
set /a SESSION+=1 >nul
set /a CYCLE+=1 >nul
set "TAG=0000!CYCLE!"
set "TAG=!TAG:~-4!"
set "CYCLE_LOG=%LOG_DIR%\cycle-!TAG!.log"
set "CYCLE_LAST=%LOG_DIR%\cycle-!TAG!-result.txt"
set "CHECK_LOG=%LOG_DIR%\cycle-!TAG!-check.log"
set "GATE_LOG=%LOG_DIR%\cycle-!TAG!-gate.log"
set "MEASURE_LOG=%LOG_DIR%\cycle-!TAG!-measure.log"
set "MEASURE_OUT=%PERF_PREFIX%!TAG!.tsv"
set "START_DATE=%DATE%"
set "START_TIME=%TIME%"

echo.
echo [%DATE% %TIME%] ---------- cycle !CYCLE! starting ----------
call :run_codex
if errorlevel 3 (
    echo [%DATE% %TIME%] ---------- stopping after cycle !CYCLE! ----------
    exit /b 1
)
call :check
call :measure
call :record

if %FAIL_EXIT_LIMIT% gtr 0 if !FAILS! geq %FAIL_EXIT_LIMIT% (
    echo [%DATE% %TIME%] codex exited nonzero !FAILS! times in a row; inspect !CYCLE_LOG!.
    echo [%DATE% %TIME%] ---------- stopping after cycle !CYCLE! ----------
    exit /b 1
)
if not "!RC!"=="0" (
    echo [%DATE% %TIME%] waiting %FAIL_SLEEP%s before the next cycle after a failed run.
    call :sleep %FAIL_SLEEP%
)
echo [%DATE% %TIME%] ---------- cycle !CYCLE! finished, looping ----------
goto cycle

:sleep
rem %1 = seconds.  `timeout` needs a console, so fall back to a quiet ping.
if "%~1"=="" exit /b 0
if "%~1"=="0" exit /b 0
timeout /t %~1 /nobreak >nul 2>&1
if errorlevel 1 ping -n %~1 127.0.0.1 >nul 2>&1
exit /b 0

:run_codex
set "RC=0"
set "MODEL_ARG="
if defined MODEL set "MODEL_ARG=--model "%MODEL%""
set "EFFORT_ARG="
if defined REASONING set "EFFORT_ARG=-c model_reasoning_effort="%REASONING%""
rem The prompt follows the sync: either the task, or the merge that only codex
rem can settle, or the task with the note that remote work was just merged in.
set "PROMPT=%TASK_PROMPT%"
set "PROMPT_KIND=task"
if /i "!SYNC_STATE!"=="conflict" (
    set "PROMPT=!CONFLICT_PROMPT!"
    set "PROMPT_KIND=conflict"
)
if "!PULLED!"=="1" set "PROMPT=%TASK_PROMPT% %PULL_NOTE%"
echo [%DATE% %TIME%] codex is working ^(!PROMPT_KIND! prompt^); transcript: %CYCLE_LOG%
call "%CODEX_EXE%" exec !MODEL_ARG! !EFFORT_ARG! -C "%ROOT%" --sandbox danger-full-access -c approval_policy="never" --color never -o "%CYCLE_LAST%" "!PROMPT!" > "%CYCLE_LOG%" 2>&1 <nul
set "RC=!ERRORLEVEL!"
if "!RC!"=="0" (
    set "FAILS=0"
    echo [%DATE% %TIME%] cycle !CYCLE! codex exit 0; final message: %CYCLE_LAST%
) else (
    set /a FAILS+=1 >nul
    echo [%DATE% %TIME%] cycle !CYCLE! codex exit !RC!; consecutive failure !FAILS!
    rem An account usage limit is not a broken cycle: stop instead of retrying into it.
    findstr /i /c:"usage limit" "%CYCLE_LOG%" >nul 2>&1
    if not errorlevel 1 (
        echo [%DATE% %TIME%] codex reports an account usage limit; this is not a failure of the tree.
        echo [%DATE% %TIME%] the working tree is committed and unchanged; restart this worker when the account allows.
        exit /b 3
    )
)
exit /b 0

:check
set "CHECK_RC=-"
set "GATE_RC=-"
if "%NO_CHECK%"=="1" exit /b 0
if not exist "%CHECK_EXE%" (
    echo [%DATE% %TIME%] no %CHECK_EXE%; area probe skipped.
) else (
    "%CHECK_EXE%" %CHECK_ARGS% > "%CHECK_LOG%" 2>&1
    set "CHECK_RC=!ERRORLEVEL!"
    if "!CHECK_RC!"=="0" (
        echo [%DATE% %TIME%] probe ok   : %CHECK_ARGS% [%CHECK_EXE%]
    ) else (
        echo [%DATE% %TIME%] probe FAIL : %CHECK_ARGS% exit !CHECK_RC!; %CHECK_LOG%
        type "%CHECK_LOG%"
    )
)
if "%GATE%"=="1" if exist "%GATE_EXE%" (
    "%GATE_EXE%" -Regression > "%GATE_LOG%" 2>&1
    set "GATE_RC=!ERRORLEVEL!"
    if "!GATE_RC!"=="0" (
        echo [%DATE% %TIME%] gate ok    : Compatibility regression
    ) else (
        echo [%DATE% %TIME%] gate FAIL  : Compatibility regression exit !GATE_RC!; %GATE_LOG%
        type "%GATE_LOG%"
    )
)
rem The next cycle publishes this tree only if the probe just passed it.
set "LAST_CHECK_OK=1"
if not "!CHECK_RC!"=="0" if not "!CHECK_RC!"=="-" set "LAST_CHECK_OK=0"
if not "!GATE_RC!"=="-" if not "!GATE_RC!"=="0" set "LAST_CHECK_OK=0"
> "%LOG_DIR%\gate-state.txt" echo !LAST_CHECK_OK!
exit /b 0

:measure
set "MEASURE_RC=-"
if "%NO_MEASURE%"=="1" exit /b 0
if not exist "%ROOT%\cpc.exe" (
    echo [%DATE% %TIME%] no root cpc.exe; speed measurement skipped.
    exit /b 0
)
if not exist "%ROOT%\src\scripts\performance.exe" (
    echo [%DATE% %TIME%] no src\scripts\performance.exe; speed measurement skipped.
    exit /b 0
)
"%ROOT%\src\scripts\performance.exe" -Root "%ROOT%" %PERF_ARGS% -Results "%MEASURE_OUT%" > "%MEASURE_LOG%" 2>&1
set "MEASURE_RC=!ERRORLEVEL!"
if "!MEASURE_RC!"=="0" (
    echo [%DATE% %TIME%] measured     : %MEASURE_OUT%
) else (
    echo [%DATE% %TIME%] measure FAIL : exit !MEASURE_RC!; %MEASURE_LOG%
    type "%MEASURE_LOG%"
)
if exist "%MEASURE_OUT%" findstr /b /c:"c.self.driver" /c:"c.empty.main" "%MEASURE_OUT%"
exit /b 0

:record
set "ROW=!CYCLE!;%TITLE%;!START_DATE!;!START_TIME!;%DATE%;%TIME%;codex=!RC!;check=!CHECK_RC!;gate=!GATE_RC!;measure=!MEASURE_RC!;sync=!SYNC_STATE!;head=!HEAD!"
>>"%CYCLES%" echo !ROW!
echo [%DATE% %TIME%] cycle !CYCLE! recorded: codex=!RC! check=!CHECK_RC! gate=!GATE_RC! measure=!MEASURE_RC! sync=!SYNC_STATE! head=!HEAD!
exit /b 0

:read_last
set "CYCLE=0"
set "LASTROW="
if not exist "%CYCLES%" exit /b 0
for /f "usebackq tokens=1,* delims=;" %%A in ("%CYCLES%") do (
    set "CYCLE=%%A"
    set "LASTROW=%%A;%%B"
)
echo !CYCLE!|findstr /r "^[0-9][0-9]*$" >nul
if errorlevel 1 (
    set "CYCLE=0"
    set "LASTROW="
)
exit /b 0

:show_measure
set "NEWEST="
if not exist "%PERF_PREFIX%*.tsv" exit /b 0
for /f "delims=" %%F in ('dir /b /o-n "%PERF_PREFIX%*.tsv" 2^>nul') do if not defined NEWEST set "NEWEST=%%F"
if not defined NEWEST exit /b 0
echo [%DATE% %TIME%] last measured: %LOG_DIR%\!NEWEST!
findstr /b /c:"c.self.driver" /c:"c.empty.main" "%LOG_DIR%\!NEWEST!"
exit /b 0

:commit_work
if "%SKIP_COMMIT%"=="1" (
    echo [%DATE% %TIME%] SKIP_COMMIT=1: leaving the working tree alone.
    exit /b 0
)
call :rebase_active
if "!REBASE_ACTIVE!"=="1" (
    echo [%DATE% %TIME%] a rebase is in progress; the tree stays as it is for codex to finish.
    exit /b 0
)
git add -A
git diff --cached --quiet >nul 2>&1
if not errorlevel 1 (
    echo [%DATE% %TIME%] working tree already clean.
    exit /b 0
)
git commit -m "%TITLE% cycle !CYCLE! %DATE% on %COMPUTERNAME%" >nul 2>&1
if errorlevel 1 (
    echo [%DATE% %TIME%] commit failed; the working tree keeps the work as it is.
    exit /b 0
)
for /f "delims=" %%H in ('git rev-parse --short HEAD 2^>nul') do set "HEAD=%%H"
echo [%DATE% %TIME%] committed the work of cycle !CYCLE! as !HEAD!.
exit /b 0

:sync
rem ---------------------------------------------------------------------------
rem Cycle-boundary protocol with the other machines that share this branch.
rem ---------------------------------------------------------------------------
set "SYNC_STATE=-"
set "SYNC_RC=0"
set "PUSH_RC=-"
set "SYNC_TRIES_RUN=0"
set "CONFLICT_LIST="
set "CONFLICT_COUNT=0"
set "CONFLICT_SOURCE=0"
set "CONFLICT_PROMPT="
set "PULLED=0"
set "NEW_UPSTREAM=0"
if "%SKIP_SYNC%"=="1" (
    echo [%DATE% %TIME%] SKIP_SYNC=1: no fetch, no rebase and no push.
    set "SYNC_STATE=off"
    exit /b 0
)
if "%SKIP_COMMIT%"=="1" (
    echo [%DATE% %TIME%] SKIP_COMMIT=1 leaves the tree free to be dirty, so sync is skipped with it.
    set "SYNC_STATE=off"
    exit /b 0
)
call :resolve_branch
call :rebase_active
if "!REBASE_ACTIVE!"=="1" (
    echo [%DATE% %TIME%] an unfinished rebase is in this tree; finishing that first.
    call :rebase_onto
)
if "!REBASE_ACTIVE!"=="1" (
    call :sync_mark_conflict
    exit /b 0
)
if /i "!BRANCH!"=="HEAD" (
    echo [%DATE% %TIME%] HEAD is detached; no fetch, no rebase and no push this cycle.
    set "SYNC_STATE=off"
    exit /b 0
)
if "!SYNC_STATE!"=="error" exit /b 0

:sync_attempt
set /a SYNC_TRIES_RUN+=1 >nul
git fetch --prune "%REMOTE%" > "%SYNC_LOG%" 2>&1
if errorlevel 1 goto sync_offline
git rev-parse --verify --quiet "refs/remotes/!UPSTREAM!" >nul 2>&1
if errorlevel 1 (
    echo [%DATE% %TIME%] %REMOTE% has no !BRANCH! branch yet; this cycle publishes the first one.
    set "NEW_UPSTREAM=1"
    call :push_work
    exit /b 0
)
call :rebase_onto
if "!REBASE_ACTIVE!"=="1" (
    call :sync_mark_conflict
    exit /b 0
)
if "!SYNC_STATE!"=="error" exit /b 0
call :push_work
if "!PUSH_RC!"=="0" exit /b 0
if "!PUSH_RC!"=="2" exit /b 0
if !SYNC_TRIES_RUN! geq %SYNC_TRIES% (
    set "SYNC_STATE=deferred"
    echo [%DATE% %TIME%] !UPSTREAM! refused the push !SYNC_TRIES_RUN! times; the work stays local and the next cycle publishes it.
    exit /b 0
)
echo [%DATE% %TIME%] another machine published first; fetching, rebasing and pushing again in %SYNC_SLEEP%s.
call :sleep %SYNC_SLEEP%
goto sync_attempt

:sync_offline
set "SYNC_RC=1"
set "SYNC_STATE=offline"
echo [%DATE% %TIME%] fetch from %REMOTE% failed; this cycle works offline: %SYNC_LOG%
type "%SYNC_LOG%"
exit /b 0

:sync_mark_conflict
call :conflict_prompt
set "SYNC_STATE=conflict"
echo [%DATE% %TIME%] a source conflict with !UPSTREAM! waits for codex:!CONFLICT_LIST!
exit /b 0

:push_work
rem Publish what the rebase left in front of !UPSTREAM!. PUSH_RC is 0 when the
rem remote took the work, 1 when it refused the push, and 2 when this clone
rem decided to keep the commits local.
set "PUSH_RC=2"
set "AHEAD=0"
if "!NEW_UPSTREAM!"=="1" (
    for /f "delims=" %%N in ('git rev-list --count HEAD 2^>nul') do set "AHEAD=%%N"
) else (
    for /f "delims=" %%N in ('git rev-list --count "!UPSTREAM!..HEAD" 2^>nul') do set "AHEAD=%%N"
)
if "!AHEAD!"=="0" exit /b 0
if "%SKIP_PUSH%"=="1" (
    set "SYNC_STATE=nopush"
    echo [%DATE% %TIME%] SKIP_PUSH=1: !AHEAD! commit^(s^) stay local.
    exit /b 0
)
if not "%PUSH_FAILED%"=="1" if "!LAST_CHECK_OK!"=="0" (
    set "SYNC_STATE=unpublished"
    echo [%DATE% %TIME%] the last probe failed, so !AHEAD! commit^(s^) stay local for the cycle that repairs them; set PUSH_FAILED=1 to publish anyway.
    exit /b 0
)
git push "%REMOTE%" "HEAD:refs/heads/!BRANCH!" > "%PUSH_LOG%" 2>&1
if errorlevel 1 (
    set "PUSH_RC=1"
    echo [%DATE% %TIME%] push refused, usually because another machine published first: %PUSH_LOG%
    type "%PUSH_LOG%"
    exit /b 0
)
set "PUSH_RC=0"
set "SYNC_STATE=pushed"
for /f "delims=" %%H in ('git rev-parse --short HEAD 2^>nul') do set "HEAD=%%H"
if "!NEW_UPSTREAM!"=="1" (
    echo [%DATE% %TIME%] published the first !BRANCH! to %REMOTE% at !HEAD! ^(!AHEAD! commit^(s^)^).
) else (
    echo [%DATE% %TIME%] published !AHEAD! commit^(s^) to !UPSTREAM! at !HEAD!.
)
exit /b 0

:rebase_onto
rem Rebase this clone's unpushed commits onto !UPSTREAM!. A conflict in a tracked
rem build output is resolved here with this clone's copy; a conflict in a source
rem file leaves REBASE_ACTIVE=1 so codex resolves it this cycle.
set "SYNC_STATE=clean"
set "REBASE_RC=0"
set "BEHIND=0"
call :rebase_active
if "!REBASE_ACTIVE!"=="0" (
    for /f "delims=" %%N in ('git rev-list --count "HEAD..!UPSTREAM!" 2^>nul') do set "BEHIND=%%N"
    if "!BEHIND!"=="0" exit /b 0
    echo [%DATE% %TIME%] rebasing this clone onto !UPSTREAM! ^(!BEHIND! new commit^(s^)^).
    git -c core.editor=true rebase "!UPSTREAM!" > "%SYNC_LOG%" 2>&1
    set "REBASE_RC=!ERRORLEVEL!"
    call :rebase_active
)
if "!REBASE_ACTIVE!"=="0" goto rebase_settled
set "HOP=0"
:rebase_hop
set /a HOP+=1 >nul
call :resolve_generated
if "!CONFLICT_SOURCE!"=="1" exit /b 0
if "!CONFLICT_COUNT!"=="0" if !HOP! gtr 1 exit /b 0
if "!CONFLICT_COUNT!"=="0" (
    echo [%DATE% %TIME%] the rebase has no unmerged path left; continuing it.
) else (
    echo [%DATE% %TIME%] keeping this clone's !RESOLVED_COUNT! build output^(s^) and continuing the rebase.
)
git -c core.editor=true rebase --continue >> "%SYNC_LOG%" 2>&1
set "REBASE_RC=!ERRORLEVEL!"
call :rebase_active
if "!REBASE_ACTIVE!"=="1" if !HOP! lss 20 goto rebase_hop
:rebase_settled
call :rebase_active
if "!REBASE_ACTIVE!"=="1" exit /b 0
if "!REBASE_RC!"=="0" (
    set "SYNC_STATE=pulled"
    set "PULLED=1"
    exit /b 0
)
set "SYNC_STATE=error"
echo [%DATE% %TIME%] rebase onto !UPSTREAM! failed; this cycle stays local: %SYNC_LOG%
type "%SYNC_LOG%"
exit /b 0

:resolve_generated
rem Resolve every unmerged tracked build output with this clone's copy and say
rem whether a conflict is left that only codex can weigh.
set "CONFLICT_LIST="
set "CONFLICT_COUNT=0"
set "RESOLVED_COUNT=0"
set "CONFLICT_SOURCE=0"
for /f "delims=" %%F in ('git diff --name-only --diff-filter=U 2^>nul') do (
    set /a CONFLICT_COUNT+=1 >nul
    call :is_generated "%%F"
    if "!GENERATED!"=="1" (
        git checkout --theirs -- "%%F" >nul 2>&1
        if errorlevel 1 (
            set "CONFLICT_SOURCE=1"
            set "CONFLICT_LIST=!CONFLICT_LIST! %%F"
        ) else (
            git add -- "%%F" >nul 2>&1
            set /a RESOLVED_COUNT+=1 >nul
            echo [%DATE% %TIME%] kept this clone's %%F through the rebase.
        )
    ) else (
        set "CONFLICT_SOURCE=1"
        set "CONFLICT_LIST=!CONFLICT_LIST! %%F"
    )
)
exit /b 0

:is_generated
rem %1 = a path as git reports it. Every tracked executable and the bootstrap
rem runtime archive is produced by the build in this tree, so a rebase keeps the
rem copy this clone just made instead of merging bytes.
set "GENERATED=0"
set "GENPATH=%~1"
if /i "!GENPATH:~-4!"==".exe" set "GENERATED=1"
if /i "!GENPATH!"=="src/lib/libcprime1.a" set "GENERATED=1"
exit /b 0

:conflict_prompt
rem A merge that cannot be settled mechanically belongs to codex.
if "!CONFLICT_COUNT!"=="0" set "CONFLICT_LIST= none reported; inspect git status"
set "CONFLICT_PROMPT=The tree is in the middle of a git rebase onto %UPSTREAM% that cannot be finished without dropping somebody's work. Resolve every conflicted path so that both sides keep their intent: this repository is shared by three concurrent workers (Capability, Compatibility and Cost) and no side may lose work to make the merge easy. Conflicted paths:!CONFLICT_LIST!. Work under AGENTS.md: root cpc.exe only, one compiler process at a time, no host compiler. Run Cost\tests\test.exe -All -Tier fast and Compatibility\tests\test.exe -Regression, keep that evidence under %TITLE%\build, and finish the merge with git -c core.editor=true rebase --continue. Do not fetch, push or make any other commit, and never delete, move or rewrite %TITLE%\worker.cmd. Finish by updating %TITLE%\task.md with the remaining work and the exact next action."
exit /b 0

:rebase_active
set "REBASE_ACTIVE=0"
for /f "delims=" %%P in ('git rev-parse --git-path rebase-merge 2^>nul') do if exist "%%P" set "REBASE_ACTIVE=1"
for /f "delims=" %%P in ('git rev-parse --git-path rebase-apply 2^>nul') do if exist "%%P" set "REBASE_ACTIVE=1"
exit /b 0

:resolve_branch
if not defined REMOTE set "REMOTE=origin"
if not defined BRANCH for /f "delims=" %%B in ('git rev-parse --abbrev-ref HEAD 2^>nul') do set "BRANCH=%%B"
rem A rebase parks the checkout on a detached HEAD; the branch it will return to
rem is written down in the rebase state, and the sync needs that name.
if /i "!BRANCH!"=="HEAD" (
    set "HEADNAME="
    for /f "delims=" %%P in ('git rev-parse --git-path rebase-merge 2^>nul') do if exist "%%P\head-name" set /p HEADNAME=<"%%P\head-name"
    if defined HEADNAME set "BRANCH=!HEADNAME:refs/heads/=!"
)
if not defined BRANCH set "BRANCH=main"
if /i "!BRANCH!"=="HEAD" set "BRANCH=main"
set "UPSTREAM=%REMOTE%/%BRANCH%"
exit /b 0

:git_setup
rem rerere replays the way this clone settled a conflict last time, which is
rem what keeps three machines rebasing onto each other cheap.
git config rerere.enabled true >nul 2>&1
git config rerere.autoupdate true >nul 2>&1
exit /b 0
