#ifndef _CPC_OBJBASE_H
#define _CPC_OBJBASE_H
#include <combaseapi.h>
#include <unknwn.h>
#ifndef _OLECHAR_DEFINED
#define _OLECHAR_DEFINED
typedef WCHAR OLECHAR;
typedef OLECHAR *LPOLESTR;
typedef const OLECHAR *LPCOLESTR;
#endif
#ifndef _BSTR_DEFINED
#define _BSTR_DEFINED
typedef OLECHAR *BSTR;
#endif
typedef enum tagCOINIT { COINIT_APARTMENTTHREADED=2, COINIT_MULTITHREADED=0, COINIT_DISABLE_OLE1DDE=4, COINIT_SPEED_OVER_MEMORY=8 } COINIT;
#define CLSCTX_INPROC_SERVER 1
#define CLSCTX_INPROC_HANDLER 2
#define CLSCTX_LOCAL_SERVER 4
#define CLSCTX_REMOTE_SERVER 16
#define CLSCTX_ALL (CLSCTX_INPROC_SERVER|CLSCTX_INPROC_HANDLER|CLSCTX_LOCAL_SERVER|CLSCTX_REMOTE_SERVER)
WINOLEAPI CoInitialize(LPVOID reserved);
WINOLEAPI CoCreateGuid(GUID* guid);
WINOLEAPI CoCreateInstance(REFCLSID clsid, IUnknown* outer, DWORD context, REFIID iid, void** object);
#endif
